export const data = [
  {
    opponent: "MHk 32 Liptovský Mikuláš",
    date: "Nedeľa 23.09.2018, 17:30",
    shots: [
      { name: "BROWN, Jared", top: "57%", left: "20%" },
      { name: "POZSGAI, Tamás", top: "63%", left: "20%" },
      { name: "ORBAN, Brance", top: "78%", left: "22%" },
      { name: "ORBAN, Brance", top: "33%", left: "22%" },
      { name: "KREISZ, Brúnó", top: "51%", left: "17%" },
      { name: "ODNOGA, Mátyás", top: "50%", left: "14%" },
      { name: "BURT, Cameron", top: "50%", left: "34%" },
      { name: "DUDÁS, Jesse Ray", top: "35%", left: "11%" },
      { name: "KLEMPA, Tomáš", top: "34%", left: "70%" },
      { name: "BODÓ, Chris", top: "74%", left: "65%" },
      { name: "PÁPA, Márton", top: "43%", left: "88%" },
      { name: "BURT, Cameron", top: "63%", left: "64%" },
      { name: "KLEMPA, Tomáš", top: "55%", left: "87%" },
      { name: "BROWN, Jared", top: "36%", left: "84%" },
      { name: "KREISZ, Brúnó", top: "64%", left: "85%" },
      { name: "SZABAD, Kevin", top: "34%", left: "74%" },
      { name: "PÁPA, Márton", top: "41%", left: "83%" },
      { name: "SZABAD, Kevin", top: "33%", left: "23%" },
      { name: "SZABAD, Kevin", top: "52%", left: "17%" },
      { name: "MACAULAY, Scott", top: "91%", left: "9%" },
      { name: "DUDÁS, Jesse Ray", top: "21%", left: "32%" },
      { name: "SZABAD, Kevin", top: "40%", left: "12%" },
      { name: "DUDÁS, Jesse Ray", top: "69%", left: "33%" },
      { name: "LANGKOW, Chris", top: "77%", left: "21%" },
      { name: "DUDÁS, Jesse Ray", top: "90%", left: "21%" }
    ]
  },
  {
    opponent: "HC 07 Detva",
    date: "Nedeľa 07.10.2018, 18:00",
    shots: [
      { name: "SZABAD, Kevin", top: "23%", left: "77%" },
      { name: "POZSGAI, Tamás", top: "50%", left: "31%" },
      { name: "LANGKOW, Chris", top: "60%", left: "27%" },
      { name: "ODNOGA, Mátyás", top: "48%", left: "19%" },
      { name: "LANGKOW, Chris", top: "89%", left: "31%" },
      { name: "POZSGAI, Tamás", top: "85%", left: "72%" },
      { name: "SZIGETI, Ákos", top: "80%", left: "69%" },
      { name: "LANGKOW, Chris", top: "50%", left: "24%" },
      { name: "BROWN, Jared", top: "44%", left: "70%" },
      { name: "TERBÓCS, István", top: "49%", left: "84%" },
      { name: "BODÓ, Chris", top: "27%", left: "65%" },
      { name: "NAGY, Krisztián", top: "59%", left: "87%" },
      { name: "BROWN, Jared", top: "79%", left: "89%" },
      { name: "NAGY, Krisztián", top: "42%", left: "87%" },
      { name: "KLEMPA, Tomáš", top: "10%", left: "76%" },
      { name: "TERBÓCS, István", top: "81%", left: "76%" },
      { name: "KLEMPA, Tomáš", top: "52%", left: "77%" },
      { name: "BODÓ, Chris", top: "48%", left: "19%" },
      { name: "MACAULAY, Scott", top: "17%", left: "26%" },
      { name: "DUDÁS, Jesse Ray", top: "82%", left: "28%" },
      { name: "DANSEREAU, Keegan", top: "75%", left: "17%" },
      { name: "DUDÁS, Jesse Ray", top: "57%", left: "32%" },
      { name: "TERBÓCS, István", top: "29%", left: "10%" },
      { name: "TERBÓCS, István", top: "51%", left: "12%" },
      { name: "BODÓ, Chris", top: "49%", left: "19%" }
    ]
  },
  {
    opponent: "HK Nitra",
    date: "Piatok 28.09.2018, 19:00",
    shots: [
      { name: "DANSEREAU, Keegan", top: "92%", left: "32%" },
      { name: "POZSGAI, Tamás", top: "91%", left: "32%" },
      { name: "LANGKOW, Chris", top: "8%", left: "17%" },
      { name: "DUDÁS, Jesse Ray", top: "50%", left: "32%" },
      { name: "KLEMPA, Tomáš", top: "77%", left: "29%" },
      { name: "KLEMPA, Tomáš", top: "50%", left: "12%" },
      { name: "TERBÓCS, István", top: "15%", left: "17%" },
      { name: "POZSGAI, Tamás", top: "89%", left: "31%" },
      { name: "KLEMPA, Tomáš", top: "39%", left: "23%" },
      { name: "DUDÁS, Jesse Ray", top: "92%", left: "31%" },
      { name: "DUDÁS, Jesse Ray", top: "19%", left: "29%" },
      { name: "ODNOGA, Mátyás", top: "23%", left: "21%" },
      { name: "KLEMPA, Tomáš", top: "59%", left: "69%" },
      { name: "NAGY, Krisztián", top: "36%", left: "69%" },
      { name: "BROWN, Jared", top: "80%", left: "73%" },
      { name: "NAGY, Krisztián", top: "48%", left: "78%" },
      { name: "SZIGETI, Ákos", top: "37%", left: "67%" },
      { name: "TERBÓCS, István", top: "38%", left: "70%" },
      { name: "DUDÁS, Jesse Ray", top: "76%", left: "28%" },
      { name: "DUDÁS, Jesse Ray", top: "86%", left: "27%" },
      { name: "BROWN, Jared", top: "50%", left: "20%" },
      { name: "NAGY, Krisztián", top: "40%", left: "12%" },
      { name: "BODÓ, Chris", top: "85%", left: "13%" },
      { name: "NAGY, Krisztián", top: "62%", left: "7%" },
      { name: "TERBÓCS, István", top: "74%", left: "17%" },
      { name: "BURT, Cameron", top: "45%", left: "10%" },
      { name: "DANSEREAU, Keegan", top: "52%", left: "18%" },
      { name: "NAGY, Krisztián", top: "67%", left: "32%" },
      { name: "DANSEREAU, Keegan", top: "63%", left: "11%" }
    ]
  },
  {
    opponent: "MHC MIKRON Nové Zámky",
    date: "Piatok 14.09.2018, 19:00",
    shots: [
      { name: "ODNOGA, Mátyás", top: "67%", left: "15%" },
      { name: "KLEMPA, Tomáš", top: "83%", left: "21%" },
      { name: "POZSGAI, Tamás", top: "73%", left: "32%" },
      { name: "LANGKOW, Chris", top: "27%", left: "16%" },
      { name: "MACAULAY, Scott", top: "53%", left: "34%" },
      { name: "MACAULAY, Scott", top: "32%", left: "15%" },
      { name: "LANGKOW, Chris", top: "35%", left: "27%" },
      { name: "DANSEREAU, Keegan", top: "45%", left: "31%" },
      { name: "DUDÁS, Jesse Ray", top: "67%", left: "14%" },
      { name: "POZSGAI, Tamás", top: "15%", left: "54%" },
      { name: "VOKLA, Roland", top: "65%", left: "64%" },
      { name: "NAGY, Krisztián", top: "9%", left: "69%" },
      { name: "MACAULAY, Scott", top: "45%", left: "68%" },
      { name: "DUDÁS, Jesse Ray", top: "12%", left: "69%" },
      { name: "BURT, Cameron", top: "62%", left: "64%" },
      { name: "TERBÓCS, István", top: "36%", left: "90%" },
      { name: "KLEMPA, Tomáš", top: "40%", left: "87%" },
      { name: "POZSGAI, Tamás", top: "72%", left: "65%" },
      { name: "DANSEREAU, Keegan", top: "10%", left: "22%" },
      { name: "MACAULAY, Scott", top: "18%", left: "20%" },
      { name: "NAGY, Krisztián", top: "34%", left: "18%" },
      { name: "BURT, Cameron", top: "84%", left: "27%" },
      { name: "KLEMPA, Tomáš", top: "53%", left: "29%" },
      { name: "KLEMPA, Tomáš", top: "27%", left: "17%" },
      { name: "BROWN, Jared", top: "29%", left: "19%" }
    ]
  },
  {
    opponent: "HK Poprad",
    date: "Nedeľa 16.09.2018, 17:00",
    shots: [
      { name: "TERBÓCS, István", top: "78%", left: "17%" },
      { name: "SZABAD, Kevin", top: "80%", left: "23%" },
      { name: "SZABAD, Kevin", top: "70%", left: "19%" },
      { name: "BROWN, Jared", top: "81%", left: "30%" },
      { name: "DANSEREAU, Keegan", top: "47%", left: "23%" },
      { name: "BROWN, Jared", top: "43%", left: "18%" },
      { name: "MACAULAY, Scott", top: "77%", left: "16%" },
      { name: "KLEMPA, Tomáš", top: "57%", left: "19%" },
      { name: "BROWN, Jared", top: "33%", left: "22%" },
      { name: "NAGY, Krisztián", top: "59%", left: "18%" },
      { name: "FEJES, Nándor", top: "46%", left: "25%" },
      { name: "BROWN, Jared", top: "71%", left: "28%" },
      { name: "BROWN, Jared", top: "26%", left: "22%" },
      { name: "DANSEREAU, Keegan", top: "25%", left: "17%" },
      { name: "POZSGAI, Tamás", top: "41%", left: "73%" },
      { name: "ORBAN, Brance", top: "28%", left: "19%" },
      { name: "VOKLA, Roland", top: "29%", left: "70%" },
      { name: "NAGY, Krisztián", top: "28%", left: "75%" },
      { name: "BODÓ, Chris", top: "30%", left: "82%" },
      { name: "NAGY, Krisztián", top: "74%", left: "76%" },
      { name: "TERBÓCS, István", top: "58%", left: "71%" }
    ]
  },
  {
    opponent: "HKM Zvolen",
    date: "Piatok 05.10.2018, 18:00",
    shots: [
      { name: "TERBÓCS, István", top: "79%", left: "82%" },
      { name: "LANGKOW, Chris", top: "57%", left: "77%" },
      { name: "GARÁT, Zsombor", top: "63%", left: "84%" },
      { name: "BROWN, Jared", top: "59%", left: "77%" },
      { name: "BROWN, Jared", top: "46%", left: "40%" },
      { name: "BODÓ, Chris", top: "53%", left: "54%" },
      { name: "BROWN, Jared", top: "68%", left: "80%" },
      { name: "TERBÓCS, István", top: "69%", left: "79%" },
      { name: "VOKLA, Roland", top: "63%", left: "82%" },
      { name: "DANSEREAU, Keegan", top: "63%", left: "81%" },
      { name: "BROWN, Jared", top: "67%", left: "80%" },
      { name: "VOKLA, Roland", top: "64%", left: "77%" },
      { name: "BROWN, Jared", top: "61%", left: "81%" },
      { name: "TERBÓCS, István", top: "56%", left: "78%" },
      { name: "DANSEREAU, Keegan", top: "58%", left: "83%" },
      { name: "LANGKOW, Chris", top: "54%", left: "84%" },
      { name: "GARÁT, Zsombor", top: "76%", left: "49%" },
      { name: "NAGY, Krisztián", top: "70%", left: "82%" },
      { name: "NAGY, Krisztián", top: "70%", left: "46%" },
      { name: "LANGKOW, Chris", top: "62%", left: "82%" },
      { name: "BODÓ, Chris", top: "60%", left: "83%" },
      { name: "BODÓ, Chris", top: "72%", left: "85%" },
      { name: "TERBÓCS, István", top: "54%", left: "79%" },
      { name: "SZABAD, Kevin", top: "76%", left: "81%" },
      { name: "DANSEREAU, Keegan", top: "72%", left: "79%" },
      { name: "DANSEREAU, Keegan", top: "62%", left: "81%" }
    ]
  },
  {
    opponent: "HK DUKLA Trenčín",
    date: "Piatok 21.09.2018, 18:00",
    shots: [
      { name: "BODÓ, Chris", top: "47%", left: "80%" },
      { name: "SZABAD, Kevin", top: "59%", left: "88%" },
      { name: "ORBAN, Brance", top: "22%", left: "75%" },
      { name: "KREISZ, Brúnó", top: "45%", left: "83%" },
      { name: "NAGY, Krisztián", top: "37%", left: "84%" },
      { name: "DUDÁS, Jesse Ray", top: "28%", left: "75%" },
      { name: "POZSGAI, Tamás", top: "61%", left: "81%" },
      { name: "BROWN, Jared", top: "61%", left: "12%" },
      { name: "NAGY, Krisztián", top: "53%", left: "83%" },
      { name: "ORBAN, Brance", top: "46%", left: "24%" },
      { name: "KLEMPA, Tomáš", top: "31%", left: "22%" },
      { name: "DANSEREAU, Keegan", top: "58%", left: "19%" },
      { name: "SZABAD, Kevin", top: "78%", left: "20%" },
      { name: "BODÓ, Chris", top: "38%", left: "23%" },
      { name: "BROWN, Jared", top: "19%", left: "72%" },
      { name: "BROWN, Jared", top: "59%", left: "89%" },
      { name: "DUDÁS, Jesse Ray", top: "32%", left: "68%" },
      { name: "DANSEREAU, Keegan", top: "61%", left: "79%" },
      { name: "MACAULAY, Scott", top: "29%", left: "69%" },
      { name: "BROWN, Jared", top: "24%", left: "84%" },
      { name: "KLEMPA, Tomáš", top: "50%", left: "77%" },
      { name: "DANSEREAU, Keegan", top: "47%", left: "31%" },
      { name: "SZABAD, Kevin", top: "15%", left: "77%" }
    ]
  },
  {
    opponent: "DVTK Jegesmedvék Miskolc",
    date: "Piatok 12.10.2018, 18:00",
    shots: [
      { name: "MACAULAY, Scott", top: "59%", left: "11%" },
      { name: "LANGKOW, Chris", top: "71%", left: "13%" },
      { name: "KLEMPA, Tomáš", top: "30%", left: "13%" },
      { name: "NAGY, Krisztián", top: "33%", left: "12%" },
      { name: "BODÓ, Chris", top: "64%", left: "89%" },
      { name: "DUDÁS, Jesse Ray", top: "66%", left: "75%" },
      { name: "ORBAN, Brance", top: "8%", left: "75%" },
      { name: "VOKLA, Roland", top: "45%", left: "73%" },
      { name: "DUDÁS, Jesse Ray", top: "68%", left: "71%" },
      { name: "POZSGAI, Tamás", top: "57%", left: "74%" },
      { name: "DANSEREAU, Keegan", top: "35%", left: "78%" },
      { name: "NAGY, Krisztián", top: "50%", left: "85%" },
      { name: "ORBAN, Brance", top: "66%", left: "84%" },
      { name: "BROWN, Jared", top: "67%", left: "79%" },
      { name: "LANGKOW, Chris", top: "15%", left: "81%" },
      { name: "DANSEREAU, Keegan", top: "42%", left: "86%" },
      { name: "NAGY, Krisztián", top: "70%", left: "88%" },
      { name: "BROWN, Jared", top: "32%", left: "11%" },
      { name: "NAGY, Krisztián", top: "66%", left: "12%" },
      { name: "GARÁT, Zsombor", top: "87%", left: "33%" },
      { name: "ODNOGA, Mátyás", top: "57%", left: "26%" },
      { name: "NAGY, Krisztián", top: "50%", left: "12%" },
      { name: "DANSEREAU, Keegan", top: "73%", left: "24%" },
      { name: "DANSEREAU, Keegan", top: "78%", left: "22%" },
      { name: "GARÁT, Zsombor", top: "53%", left: "32%" },
      { name: "TERBÓCS, István", top: "4%", left: "20%" },
      { name: "POZSGAI, Tamás", top: "40%", left: "27%" },
      { name: "DUDÁS, Jesse Ray", top: "21%", left: "24%" },
      { name: "KLEMPA, Tomáš", top: "38%", left: "11%" },
      { name: "MACAULAY, Scott", top: "30%", left: "32%" },
      { name: "BROWN, Jared", top: "24%", left: "9%" },
      { name: "NAGY, Krisztián", top: "47%", left: "78%" },
      { name: "KLEMPA, Tomáš", top: "42%", left: "12%" }
    ]
  },
  {
    opponent: "MsHK DOXXbet Žilina",
    date: "Nedeľa 30.09.2018, 17:00",
    shots: [
      { name: "TERBÓCS, István", top: "59%", left: "12%" },
      { name: "MACAULAY, Scott", top: "13%", left: "33%" },
      { name: "SZABAD, Kevin", top: "86%", left: "29%" },
      { name: "NAGY, Krisztián", top: "30%", left: "33%" },
      { name: "GARÁT, Zsombor", top: "41%", left: "28%" },
      { name: "KLEMPA, Tomáš", top: "38%", left: "83%" },
      { name: "FEJES, Nándor", top: "61%", left: "81%" },
      { name: "PÁPA, Márton", top: "29%", left: "85%" },
      { name: "NAGY, Krisztián", top: "35%", left: "82%" },
      { name: "ODNOGA, Mátyás", top: "44%", left: "78%" },
      { name: "LANGKOW, Chris", top: "61%", left: "83%" },
      { name: "POZSGAI, Tamás", top: "37%", left: "63%" },
      { name: "PÁPA, Márton", top: "39%", left: "78%" },
      { name: "BROWN, Jared", top: "52%", left: "65%" },
      { name: "NAGY, Krisztián", top: "42%", left: "41%" },
      { name: "LANGKOW, Chris", top: "22%", left: "31%" },
      { name: "TERBÓCS, István", top: "42%", left: "20%" },
      { name: "BODÓ, Chris", top: "62%", left: "17%" },
      { name: "TERBÓCS, István", top: "63%", left: "23%" },
      { name: "BROWN, Jared", top: "24%", left: "37%" },
      { name: "NAGY, Krisztián", top: "41%", left: "31%" },
      { name: "ODNOGA, Mátyás", top: "64%", left: "24%" },
      { name: "BURT, Cameron", top: "57%", left: "33%" }
    ]
  },
  {
    opponent: "MHC MIKRON Nové Zámky",
    date: "Nedeľa 14.10.2018, 16:00",
    shots: [
      { name: "ORBAN, Brance", top: "88%", left: "11%" },
      { name: "BODÓ, Chris", top: "67%", left: "20%" },
      { name: "MACAULAY, Scott", top: "26%", left: "23%" },
      { name: "MACAULAY, Scott", top: "66%", left: "76%" },
      { name: "ORBAN, Brance", top: "28%", left: "84%" },
      { name: "BROWN, Jared", top: "83%", left: "12%" },
      { name: "LANGKOW, Chris", top: "11%", left: "83%" },
      { name: "DUDÁS, Jesse Ray", top: "21%", left: "30%" },
      { name: "GARÁT, Zsombor", top: "53%", left: "23%" },
      { name: "LANGKOW, Chris", top: "12%", left: "22%" },
      { name: "KLEMPA, Tomáš", top: "49%", left: "12%" },
      { name: "KLEMPA, Tomáš", top: "21%", left: "21%" },
      { name: "DUDÁS, Jesse Ray", top: "10%", left: "21%" },
      { name: "BODÓ, Chris", top: "44%", left: "16%" },
      { name: "GARÁT, Zsombor", top: "78%", left: "28%" },
      { name: "DUDÁS, Jesse Ray", top: "9%", left: "22%" },
      { name: "DUDÁS, Jesse Ray", top: "19%", left: "29%" },
      { name: "DANSEREAU, Keegan", top: "44%", left: "16%" },
      { name: "GARÁT, Zsombor", top: "11%", left: "75%" },
      { name: "BROWN, Jared", top: "81%", left: "69%" },
      { name: "ORBAN, Brance", top: "56%", left: "73%" },
      { name: "BROWN, Jared", top: "59%", left: "77%" },
      { name: "DANSEREAU, Keegan", top: "27%", left: "84%" },
      { name: "MACAULAY, Scott", top: "68%", left: "78%" },
      { name: "BROWN, Jared", top: "27%", left: "75%" },
      { name: "VOKLA, Roland", top: "17%", left: "74%" },
      { name: "LANGKOW, Chris", top: "47%", left: "89%" },
      { name: "ORBAN, Brance", top: "55%", left: "83%" },
      { name: "LANGKOW, Chris", top: "75%", left: "75%" },
      { name: "KLEMPA, Tomáš", top: "46%", left: "81%" },
      { name: "KLEMPA, Tomáš", top: "74%", left: "72%" },
      { name: "DUDÁS, Jesse Ray", top: "88%", left: "71%" },
      { name: "GARÁT, Zsombor", top: "22%", left: "67%" },
      { name: "DUDÁS, Jesse Ray", top: "83%", left: "72%" },
      { name: "DUDÁS, Jesse Ray", top: "87%", left: "69%" },
      { name: "DANSEREAU, Keegan", top: "71%", left: "81%" },
      { name: "BROWN, Jared", top: "61%", left: "11%" },
      { name: "BROWN, Jared", top: "29%", left: "22%" },
      { name: "BROWN, Jared", top: "9%", left: "34%" },
      { name: "ORBAN, Brance", top: "39%", left: "26%" },
      { name: "ORBAN, Brance", top: "90%", left: "29%" },
      { name: "DUDÁS, Jesse Ray", top: "25%", left: "30%" },
      { name: "LANGKOW, Chris", top: "42%", left: "11%" },
      { name: "BROWN, Jared", top: "70%", left: "28%" },
      { name: "VOKLA, Roland", top: "88%", left: "31%" },
      { name: "MACAULAY, Scott", top: "13%", left: "31%" }
    ]
  },
  {
    opponent: "HC Košice",
    date: "Utorok 02.10.2018, 19:00",
    shots: [
      { name: "NAGY, Krisztián", top: "64%", left: "18%" },
      { name: "SZABAD, Kevin", top: "44%", left: "17%" },
      { name: "POZSGAI, Tamás", top: "7%", left: "17%" },
      { name: "DANSEREAU, Keegan", top: "4%", left: "27%" },
      { name: "BROWN, Jared", top: "11%", left: "28%" },
      { name: "BODÓ, Chris", top: "55%", left: "12%" },
      { name: "BROWN, Jared", top: "51%", left: "16%" },
      { name: "BROWN, Jared", top: "3%", left: "20%" },
      { name: "MACAULAY, Scott", top: "39%", left: "35%" },
      { name: "NAGY, Krisztián", top: "52%", left: "17%" },
      { name: "DANSEREAU, Keegan", top: "60%", left: "16%" },
      { name: "KLEMPA, Tomáš", top: "46%", left: "11%" },
      { name: "SZABAD, Kevin", top: "56%", left: "10%" },
      { name: "KLEMPA, Tomáš", top: "43%", left: "88%" },
      { name: "VOKLA, Roland", top: "72%", left: "72%" },
      { name: "BURT, Cameron", top: "64%", left: "80%" },
      { name: "SZABAD, Kevin", top: "59%", left: "89%" },
      { name: "PÁPA, Márton", top: "43%", left: "87%" },
      { name: "TERBÓCS, István", top: "55%", left: "83%" },
      { name: "MACAULAY, Scott", top: "50%", left: "88%" },
      { name: "KLEMPA, Tomáš", top: "11%", left: "88%" },
      { name: "KLEMPA, Tomáš", top: "59%", left: "84%" },
      { name: "BURT, Cameron", top: "71%", left: "91%" },
      { name: "DANSEREAU, Keegan", top: "65%", left: "73%" },
      { name: "POZSGAI, Tamás", top: "12%", left: "65%" },
      { name: "DANSEREAU, Keegan", top: "69%", left: "80%" },
      { name: "BODÓ, Chris", top: "21%", left: "87%" },
      { name: "BROWN, Jared", top: "39%", left: "10%" },
      { name: "DANSEREAU, Keegan", top: "80%", left: "26%" },
      { name: "MACAULAY, Scott", top: "90%", left: "33%" },
      { name: "BODÓ, Chris", top: "49%", left: "25%" },
      { name: "BODÓ, Chris", top: "20%", left: "13%" },
      { name: "PÁPA, Márton", top: "64%", left: "18%" },
      { name: "KLEMPA, Tomáš", top: "93%", left: "23%" },
      { name: "POZSGAI, Tamás", top: "88%", left: "33%" },
      { name: "BROWN, Jared", top: "95%", left: "19%" },
      { name: "NAGY, Krisztián", top: "53%", left: "33%" },
      { name: "GARÁT, Zsombor", top: "89%", left: "33%" },
      { name: "POZSGAI, Tamás", top: "59%", left: "32%" }
    ]
  },
  {
    opponent: "HC ‘05 iClinic Banská Bystrica",
    date: "Utorok 18.09.2018, 19:00",
    shots: [
      { name: "SZIGETI, Ákos", top: "73%", left: "70%" },
      { name: "NAGY, Krisztián", top: "70%", left: "90%" },
      { name: "DANSEREAU, Keegan", top: "66%", left: "81%" },
      { name: "MACAULAY, Scott", top: "81%", left: "78%" },
      { name: "GARÁT, Zsombor", top: "74%", left: "70%" },
      { name: "BROWN, Jared", top: "12%", left: "69%" },
      { name: "TERBÓCS, István", top: "77%", left: "69%" },
      { name: "TERBÓCS, István", top: "72%", left: "78%" },
      { name: "POZSGAI, Tamás", top: "47%", left: "67%" },
      { name: "BURT, Cameron", top: "26%", left: "70%" },
      { name: "FEJES, Nándor", top: "67%", left: "77%" },
      { name: "ORBAN, Brance", top: "27%", left: "77%" },
      { name: "BODÓ, Chris", top: "71%", left: "67%" },
      { name: "BROWN, Jared", top: "90%", left: "78%" },
      { name: "SZABAD, Kevin", top: "61%", left: "88%" },
      { name: "SZABAD, Kevin", top: "73%", left: "72%" },
      { name: "DANSEREAU, Keegan", top: "47%", left: "75%" },
      { name: "BODÓ, Chris", top: "15%", left: "83%" },
      { name: "ORBAN, Brance", top: "86%", left: "83%" },
      { name: "TERBÓCS, István", top: "47%", left: "85%" },
      { name: "KLEMPA, Tomáš", top: "42%", left: "85%" },
      { name: "NAGY, Krisztián", top: "21%", left: "95%" },
      { name: "MACAULAY, Scott", top: "46%", left: "77%" },
      { name: "MACAULAY, Scott", top: "49%", left: "67%" },
      { name: "BROWN, Jared", top: "9%", left: "72%" },
      { name: "LANGKOW, Chris", top: "35%", left: "85%" },
      { name: "LANGKOW, Chris", top: "43%", left: "15%" },
      { name: "KLEMPA, Tomáš", top: "74%", left: "29%" },
      { name: "GARÁT, Zsombor", top: "35%", left: "31%" },
      { name: "KLEMPA, Tomáš", top: "42%", left: "27%" },
      { name: "LANGKOW, Chris", top: "46%", left: "17%" },
      { name: "DUDÁS, Jesse Ray", top: "17%", left: "28%" },
      { name: "ORBAN, Brance", top: "57%", left: "21%" },
      { name: "LANGKOW, Chris", top: "20%", left: "26%" },
      { name: "SZABAD, Kevin", top: "43%", left: "12%" },
      { name: "BROWN, Jared", top: "9%", left: "18%" },
      { name: "NAGY, Krisztián", top: "31%", left: "12%" }
    ]
  },
  {
    opponent: "HK Nitra",
    date: "Piatok 30.11.2018, 18:00",
    shots: [
      { name: "NEGRIN, John", top: "33%", left: "9%" },
      { name: "DUDÁS, Jesse Ray", top: "18%", left: "32%" },
      { name: "BROWN, Jared", top: "32%", left: "26%" },
      { name: "LANGKOW, Chris", top: "30%", left: "22%" },
      { name: "MACAULAY, Scott", top: "35%", left: "14%" },
      { name: "NAGY, Krisztián", top: "68%", left: "17%" },
      { name: "MACAULAY, Scott", top: "18%", left: "19%" },
      { name: "POZSGAI, Tamás", top: "25%", left: "31%" },
      { name: "NAGY, Krisztián", top: "24%", left: "11%" },
      { name: "MACAULAY, Scott", top: "25%", left: "31%" },
      { name: "SZABAD, Kevin", top: "71%", left: "12%" },
      { name: "DUDÁS, Jesse Ray", top: "73%", left: "75%" },
      { name: "BROWN, Jared", top: "21%", left: "86%" },
      { name: "PÁPA, Márton", top: "77%", left: "74%" },
      { name: "POZSGAI, Tamás", top: "50%", left: "68%" },
      { name: "POZSGAI, Tamás", top: "24%", left: "74%" },
      { name: "DUDÁS, Jesse Ray", top: "20%", left: "70%" },
      { name: "POZSGAI, Tamás", top: "15%", left: "82%" },
      { name: "NEGRIN, John", top: "88%", left: "29%" },
      { name: "DANSEREAU, Keegan", top: "38%", left: "11%" },
      { name: "DANSEREAU, Keegan", top: "68%", left: "28%" },
      { name: "TERBÓCS, István", top: "22%", left: "12%" },
      { name: "BROWN, Jared", top: "70%", left: "6%" },
      { name: "POZSGAI, Tamás", top: "47%", left: "32%" },
      { name: "TERBÓCS, István", top: "47%", left: "9%" },
      { name: "TERBÓCS, István", top: "27%", left: "26%" }
    ]
  },
  {
    opponent: "DVTK Jegesmedvék Miskolc",
    date: "Piatok 16.11.2018, 18:00",
    shots: [
      { name: "DANSEREAU, Keegan", top: "48%", left: "49%" },
      { name: "DUDÁS, Jesse Ray", top: "20%", left: "24%" },
      { name: "KLEMPA, Tomáš", top: "33%", left: "18%" },
      { name: "DANSEREAU, Keegan", top: "28%", left: "33%" },
      { name: "POZSGAI, Tamás", top: "33%", left: "14%" },
      { name: "BROWN, Jared", top: "27%", left: "14%" },
      { name: "ORBAN, Brance", top: "41%", left: "32%" },
      { name: "NEGRIN, John", top: "71%", left: "33%" },
      { name: "NAGY, Krisztián", top: "48%", left: "16%" },
      { name: "FEJES, Nándor", top: "31%", left: "17%" },
      { name: "KLEMPA, Tomáš", top: "55%", left: "16%" },
      { name: "DUDÁS, Jesse Ray", top: "34%", left: "18%" },
      { name: "DUDÁS, Jesse Ray", top: "68%", left: "71%" },
      { name: "LANGKOW, Chris", top: "39%", left: "65%" },
      { name: "FEJES, Nándor", top: "71%", left: "66%" },
      { name: "NAGY, Krisztián", top: "55%", left: "84%" },
      { name: "DUDÁS, Jesse Ray", top: "49%", left: "66%" },
      { name: "POZSGAI, Tamás", top: "64%", left: "68%" },
      { name: "BROWN, Jared", top: "49%", left: "77%" },
      { name: "SZABAD, Kevin", top: "70%", left: "72%" },
      { name: "LANGKOW, Chris", top: "43%", left: "90%" },
      { name: "DUDÁS, Jesse Ray", top: "56%", left: "76%" },
      { name: "KLEMPA, Tomáš", top: "54%", left: "89%" },
      { name: "KLEMPA, Tomáš", top: "34%", left: "78%" },
      { name: "BROWN, Jared", top: "27%", left: "89%" },
      { name: "DUDÁS, Jesse Ray", top: "38%", left: "15%" },
      { name: "KLEMPA, Tomáš", top: "44%", left: "15%" },
      { name: "DUDÁS, Jesse Ray", top: "18%", left: "31%" },
      { name: "DUDÁS, Jesse Ray", top: "35%", left: "13%" },
      { name: "FEJES, Nándor", top: "31%", left: "29%" },
      { name: "ORBAN, Brance", top: "41%", left: "20%" }
    ]
  },
  {
    opponent: "MHC MIKRON Nové Zámky",
    date: "Nedeľa 18.11.2018, 17:30",
    shots: [
      { name: "LANGKOW, Chris", top: "12%", left: "16%" },
      { name: "POZSGAI, Tamás", top: "16%", left: "25%" },
      { name: "NEGRIN, John", top: "38%", left: "35%" },
      { name: "ORBAN, Brance", top: "77%", left: "52%" },
      { name: "NAGY, Krisztián", top: "50%", left: "34%" },
      { name: "BODÓ, Chris", top: "73%", left: "23%" },
      { name: "NAGY, Krisztián", top: "21%", left: "24%" },
      { name: "DUDÁS, Jesse Ray", top: "45%", left: "16%" },
      { name: "BURT, Cameron", top: "43%", left: "17%" },
      { name: "DUDÁS, Jesse Ray", top: "50%", left: "28%" },
      { name: "KLEMPA, Tomáš", top: "44%", left: "11%" },
      { name: "TERBÓCS, István", top: "19%", left: "13%" },
      { name: "NEGRIN, John", top: "69%", left: "25%" },
      { name: "DUDÁS, Jesse Ray", top: "58%", left: "19%" },
      { name: "BURT, Cameron", top: "64%", left: "25%" },
      { name: "POZSGAI, Tamás", top: "32%", left: "66%" },
      { name: "POZSGAI, Tamás", top: "76%", left: "71%" },
      { name: "BODÓ, Chris", top: "64%", left: "83%" },
      { name: "TERBÓCS, István", top: "55%", left: "82%" },
      { name: "TERBÓCS, István", top: "82%", left: "71%" },
      { name: "SZIGETI, Ákos", top: "63%", left: "73%" },
      { name: "KLEMPA, Tomáš", top: "39%", left: "76%" },
      { name: "KLEMPA, Tomáš", top: "64%", left: "83%" },
      { name: "POZSGAI, Tamás", top: "22%", left: "78%" },
      { name: "LANGKOW, Chris", top: "57%", left: "73%" },
      { name: "BROWN, Jared", top: "67%", left: "82%" },
      { name: "BROWN, Jared", top: "89%", left: "41%" },
      { name: "DANSEREAU, Keegan", top: "47%", left: "76%" },
      { name: "POZSGAI, Tamás", top: "57%", left: "72%" },
      { name: "LANGKOW, Chris", top: "24%", left: "44%" },
      { name: "TERBÓCS, István", top: "27%", left: "12%" },
      { name: "BROWN, Jared", top: "65%", left: "16%" },
      { name: "BODÓ, Chris", top: "59%", left: "11%" },
      { name: "FEJES, Nándor", top: "20%", left: "13%" },
      { name: "NAGY, Krisztián", top: "78%", left: "26%" },
      { name: "NAGY, Krisztián", top: "19%", left: "20%" },
      { name: "ORBAN, Brance", top: "49%", left: "15%" },
      { name: "FEJES, Nándor", top: "29%", left: "23%" },
      { name: "DANSEREAU, Keegan", top: "62%", left: "27%" },
      { name: "DUDÁS, Jesse Ray", top: "37%", left: "11%" },
      { name: "ODNOGA, Mátyás", top: "60%", left: "14%" }
    ]
  },
  {
    opponent: "MHk 32 Liptovský Mikuláš",
    date: "Piatok 26.10.2018, 17:00",
    shots: [
      { name: "ORBAN, Brance", top: "27%", left: "79%" },
      { name: "BODÓ, Chris", top: "64%", left: "85%" },
      { name: "KLEMPA, Tomáš", top: "30%", left: "78%" },
      { name: "BURT, Cameron", top: "27%", left: "79%" },
      { name: "DANSEREAU, Keegan", top: "54%", left: "85%" },
      { name: "BROWN, Jared", top: "26%", left: "85%" },
      { name: "DUDÁS, Jesse Ray", top: "26%", left: "70%" },
      { name: "MACAULAY, Scott", top: "42%", left: "33%" },
      { name: "BURT, Cameron", top: "43%", left: "15%" },
      { name: "BURT, Cameron", top: "37%", left: "14%" },
      { name: "LANGKOW, Chris", top: "37%", left: "21%" },
      { name: "BODÓ, Chris", top: "37%", left: "11%" },
      { name: "ORBAN, Brance", top: "21%", left: "20%" },
      { name: "KREISZ, Brúnó", top: "48%", left: "26%" },
      { name: "DANSEREAU, Keegan", top: "53%", left: "30%" },
      { name: "BROWN, Jared", top: "44%", left: "16%" },
      { name: "KLEMPA, Tomáš", top: "40%", left: "12%" },
      { name: "DUDÁS, Jesse Ray", top: "75%", left: "20%" },
      { name: "KLEMPA, Tomáš", top: "73%", left: "17%" },
      { name: "DUDÁS, Jesse Ray", top: "16%", left: "20%" },
      { name: "KLEMPA, Tomáš", top: "18%", left: "72%" },
      { name: "DUDÁS, Jesse Ray", top: "67%", left: "69%" },
      { name: "DUDÁS, Jesse Ray", top: "23%", left: "71%" },
      { name: "DANSEREAU, Keegan", top: "83%", left: "74%" },
      { name: "MACAULAY, Scott", top: "44%", left: "68%" },
      { name: "ORBAN, Brance", top: "62%", left: "86%" },
      { name: "ORBAN, Brance", top: "58%", left: "87%" },
      { name: "DUDÁS, Jesse Ray", top: "53%", left: "68%" },
      { name: "LANGKOW, Chris", top: "77%", left: "75%" },
      { name: "DANSEREAU, Keegan", top: "57%", left: "78%" },
      { name: "BODÓ, Chris", top: "21%", left: "79%" },
      { name: "POZSGAI, Tamás", top: "31%", left: "67%" }
    ]
  },
  {
    opponent: "MHk 32 Liptovský Mikuláš",
    date: "Piatok 04.01.2019, 19:30",
    shots: [
      { name: "MACAULAY, Scott", top: "77%", left: "73%" },
      { name: "ORBAN, Brance", top: "58%", left: "83%" },
      { name: "TERBÓCS, István", top: "55%", left: "85%" },
      { name: "TERBÓCS, István", top: "62%", left: "86%" },
      { name: "TERBÓCS, István", top: "52%", left: "86%" },
      { name: "NAGY, Krisztián", top: "48%", left: "83%" },
      { name: "DANSEREAU, Keegan", top: "60%", left: "86%" },
      { name: "KLEMPA, Tomáš", top: "66%", left: "17%" },
      { name: "GARÁT, Zsombor", top: "36%", left: "31%" },
      { name: "POZSGAI, Tamás", top: "76%", left: "29%" },
      { name: "NEGRIN, John", top: "75%", left: "32%" },
      { name: "DANSEREAU, Keegan", top: "66%", left: "71%" },
      { name: "VOKLA, Roland", top: "40%", left: "68%" },
      { name: "VOKLA, Roland", top: "75%", left: "73%" },
      { name: "ORBAN, Brance", top: "45%", left: "83%" },
      { name: "LANGKOW, Chris", top: "39%", left: "82%" },
      { name: "LANGKOW, Chris", top: "60%", left: "85%" },
      { name: "DANSEREAU, Keegan", top: "30%", left: "85%" }
    ]
  },
  {
    opponent: "HC Košice",
    date: "Piatok 02.11.2018, 17:30",
    shots: [
      { name: "SZABAD, Kevin", top: "50%", left: "22%" },
      { name: "ODNOGA, Mátyás", top: "55%", left: "14%" },
      { name: "BODÓ, Chris", top: "62%", left: "13%" },
      { name: "LANGKOW, Chris", top: "28%", left: "21%" },
      { name: "DUDÁS, Jesse Ray", top: "16%", left: "33%" },
      { name: "ORBAN, Brance", top: "41%", left: "27%" },
      { name: "DUDÁS, Jesse Ray", top: "14%", left: "32%" },
      { name: "MAJOROSS, Barnabás", top: "39%", left: "26%" },
      { name: "POZSGAI, Tamás", top: "21%", left: "32%" },
      { name: "BUGÁR, Gábor", top: "48%", left: "80%" },
      { name: "KREISZ, Brúnó", top: "56%", left: "84%" },
      { name: "DUDÁS, Jesse Ray", top: "58%", left: "66%" },
      { name: "DANSEREAU, Keegan", top: "25%", left: "68%" },
      { name: "POZSGAI, Tamás", top: "70%", left: "80%" },
      { name: "ORBAN, Brance", top: "42%", left: "84%" },
      { name: "BROWN, Jared", top: "39%", left: "79%" },
      { name: "LANGKOW, Chris", top: "35%", left: "79%" },
      { name: "TERBÓCS, István", top: "55%", left: "82%" },
      { name: "KLEMPA, Tomáš", top: "45%", left: "70%" },
      { name: "BROWN, Jared", top: "27%", left: "18%" },
      { name: "BROWN, Jared", top: "72%", left: "15%" },
      { name: "NAGY, Krisztián", top: "61%", left: "28%" },
      { name: "DUDÁS, Jesse Ray", top: "16%", left: "34%" },
      { name: "DUDÁS, Jesse Ray", top: "16%", left: "34%" },
      { name: "DUDÁS, Jesse Ray", top: "25%", left: "27%" },
      { name: "TERBÓCS, István", top: "24%", left: "11%" }
    ]
  },
  {
    opponent: "HK DUKLA Trenčín",
    date: "Nedeľa 30.12.2018, 18:00",
    shots: [
      { name: "LANGKOW, Chris", top: "76%", left: "27%" },
      { name: "TERBÓCS, István", top: "80%", left: "23%" },
      { name: "BODÓ, Chris", top: "76%", left: "23%" },
      { name: "BROWN, Jared", top: "19%", left: "22%" },
      { name: "PÁPA, Márton", top: "35%", left: "11%" },
      { name: "TERBÓCS, István", top: "26%", left: "19%" },
      { name: "POZSGAI, Tamás", top: "81%", left: "24%" },
      { name: "KLEMPA, Tomáš", top: "76%", left: "23%" },
      { name: "BODÓ, Chris", top: "27%", left: "19%" },
      { name: "KLEMPA, Tomáš", top: "45%", left: "14%" },
      { name: "DUDÁS, Jesse Ray", top: "12%", left: "31%" },
      { name: "POZSGAI, Tamás", top: "52%", left: "86%" },
      { name: "VOKLA, Roland", top: "30%", left: "25%" },
      { name: "LANGKOW, Chris", top: "61%", left: "70%" },
      { name: "LANGKOW, Chris", top: "64%", left: "82%" },
      { name: "BROWN, Jared", top: "79%", left: "88%" },
      { name: "TERBÓCS, István", top: "66%", left: "89%" },
      { name: "DUDÁS, Jesse Ray", top: "26%", left: "88%" },
      { name: "POZSGAI, Tamás", top: "58%", left: "66%" },
      { name: "MACAULAY, Scott", top: "30%", left: "65%" },
      { name: "BODÓ, Chris", top: "49%", left: "73%" },
      { name: "POZSGAI, Tamás", top: "7%", left: "63%" },
      { name: "DUDÁS, Jesse Ray", top: "25%", left: "75%" },
      { name: "DANSEREAU, Keegan", top: "39%", left: "11%" },
      { name: "POZSGAI, Tamás", top: "53%", left: "27%" },
      { name: "ORBAN, Brance", top: "12%", left: "20%" },
      { name: "VOKLA, Roland", top: "53%", left: "26%" },
      { name: "MACAULAY, Scott", top: "20%", left: "63%" },
      { name: "DUDÁS, Jesse Ray", top: "31%", left: "72%" },
      { name: "MACAULAY, Scott", top: "70%", left: "31%" },
      { name: "KLEMPA, Tomáš", top: "13%", left: "10%" },
      { name: "ORBAN, Brance", top: "62%", left: "25%" }
    ]
  },
  {
    opponent: "HK Poprad",
    date: "Streda 26.12.2018, 18:00",
    shots: [
      { name: "LANGKOW, Chris", top: "49%", left: "19%" },
      { name: "TERBÓCS, István", top: "78%", left: "27%" },
      { name: "BROWN, Jared", top: "24%", left: "23%" },
      { name: "TERBÓCS, István", top: "47%", left: "26%" },
      { name: "LANGKOW, Chris", top: "38%", left: "35%" },
      { name: "KLEMPA, Tomáš", top: "78%", left: "24%" },
      { name: "DANSEREAU, Keegan", top: "48%", left: "27%" },
      { name: "POZSGAI, Tamás", top: "1%", left: "65%" },
      { name: "LANGKOW, Chris", top: "38%", left: "86%" },
      { name: "ORBAN, Brance", top: "56%", left: "86%" },
      { name: "DUDÁS, Jesse Ray", top: "44%", left: "66%" },
      { name: "BROWN, Jared", top: "44%", left: "81%" },
      { name: "NAGY, Krisztián", top: "24%", left: "83%" },
      { name: "BODÓ, Chris", top: "72%", left: "67%" },
      { name: "LANGKOW, Chris", top: "64%", left: "83%" },
      { name: "TERBÓCS, István", top: "28%", left: "67%" },
      { name: "ORBAN, Brance", top: "23%", left: "87%" },
      { name: "ORBAN, Brance", top: "49%", left: "24%" },
      { name: "ORBAN, Brance", top: "12%", left: "27%" },
      { name: "DANSEREAU, Keegan", top: "29%", left: "9%" },
      { name: "DANSEREAU, Keegan", top: "62%", left: "23%" },
      { name: "DUDÁS, Jesse Ray", top: "57%", left: "25%" },
      { name: "KLEMPA, Tomáš", top: "35%", left: "25%" },
      { name: "BODÓ, Chris", top: "46%", left: "31%" },
      { name: "LANGKOW, Chris", top: "82%", left: "39%" },
      { name: "NEGRIN, John", top: "72%", left: "33%" },
      { name: "ORBAN, Brance", top: "37%", left: "32%" },
      { name: "KLEMPA, Tomáš", top: "43%", left: "29%" },
      { name: "DUDÁS, Jesse Ray", top: "72%", left: "28%" },
      { name: "ORBAN, Brance", top: "84%", left: "11%" }
    ]
  },
  {
    opponent: "HK Nitra",
    date: "Nedeľa 28.10.2018, 19:00",
    shots: [
      { name: "TERBÓCS, István", top: "42%", left: "87%" },
      { name: "TERBÓCS, István", top: "56%", left: "13%" },
      { name: "DUDÁS, Jesse Ray", top: "29%", left: "33%" },
      { name: "SZABAD, Kevin", top: "62%", left: "27%" },
      { name: "DANSEREAU, Keegan", top: "55%", left: "10%" },
      { name: "DANSEREAU, Keegan", top: "5%", left: "67%" },
      { name: "POZSGAI, Tamás", top: "79%", left: "64%" },
      { name: "BODÓ, Chris", top: "58%", left: "85%" },
      { name: "SZABAD, Kevin", top: "47%", left: "77%" },
      { name: "POZSGAI, Tamás", top: "94%", left: "85%" },
      { name: "BODÓ, Chris", top: "56%", left: "68%" },
      { name: "VOKLA, Roland", top: "64%", left: "85%" },
      { name: "MACAULAY, Scott", top: "61%", left: "67%" },
      { name: "LANGKOW, Chris", top: "55%", left: "87%" },
      { name: "MAJOROSS, Barnabás", top: "53%", left: "24%" },
      { name: "DANSEREAU, Keegan", top: "68%", left: "23%" },
      { name: "KLEMPA, Tomáš", top: "61%", left: "21%" },
      { name: "LANGKOW, Chris", top: "37%", left: "16%" }
    ]
  },
  {
    opponent: "MHk 32 Liptovský Mikuláš",
    date: "Utorok 08.01.2019, 19:00",
    shots: [
      { name: "BODÓ, Chris", top: "35%", left: "16%" },
      { name: "DUDÁS, Jesse Ray", top: "47%", left: "18%" },
      { name: "DUDÁS, Jesse Ray", top: "32%", left: "17%" },
      { name: "DANSEREAU, Keegan", top: "49%", left: "21%" },
      { name: "ORBAN, Brance", top: "31%", left: "20%" },
      { name: "GARÁT, Zsombor", top: "33%", left: "27%" },
      { name: "LANGKOW, Chris", top: "38%", left: "13%" },
      { name: "NEGRIN, John", top: "47%", left: "31%" },
      { name: "LANGKOW, Chris", top: "59%", left: "29%" },
      { name: "POZSGAI, Tamás", top: "78%", left: "31%" },
      { name: "ORBAN, Brance", top: "11%", left: "87%" },
      { name: "BODÓ, Chris", top: "61%", left: "75%" },
      { name: "KLEMPA, Tomáš", top: "53%", left: "85%" },
      { name: "KLEMPA, Tomáš", top: "44%", left: "84%" },
      { name: "DANSEREAU, Keegan", top: "60%", left: "75%" },
      { name: "GARÁT, Zsombor", top: "70%", left: "66%" },
      { name: "MAJOROSS, Barnabás", top: "66%", left: "73%" },
      { name: "BODÓ, Chris", top: "55%", left: "84%" },
      { name: "BODÓ, Chris", top: "50%", left: "86%" },
      { name: "MACAULAY, Scott", top: "62%", left: "85%" },
      { name: "BROWN, Jared", top: "70%", left: "65%" },
      { name: "NEGRIN, John", top: "90%", left: "22%" },
      { name: "DUDÁS, Jesse Ray", top: "14%", left: "23%" },
      { name: "BODÓ, Chris", top: "44%", left: "13%" },
      { name: "BURT, Cameron", top: "90%", left: "32%" },
      { name: "NEGRIN, John", top: "85%", left: "27%" },
      { name: "MACAULAY, Scott", top: "33%", left: "20%" },
      { name: "BROWN, Jared", top: "80%", left: "22%" }
    ]
  },
  {
    opponent: "HC Košice",
    date: "Piatok 11.01.2019, 17:30",
    shots: [
      { name: "POZSGAI, Tamás", top: "76%", left: "30%" },
      { name: "ODNOGA, Mátyás", top: "39%", left: "14%" },
      { name: "ODNOGA, Mátyás", top: "41%", left: "23%" },
      { name: "BURT, Cameron", top: "68%", left: "14%" },
      { name: "BROWN, Jared", top: "35%", left: "20%" },
      { name: "NEGRIN, John", top: "55%", left: "16%" },
      { name: "DANSEREAU, Keegan", top: "26%", left: "12%" },
      { name: "TERBÓCS, István", top: "33%", left: "17%" },
      { name: "LANGKOW, Chris", top: "48%", left: "19%" },
      { name: "KLEMPA, Tomáš", top: "17%", left: "81%" },
      { name: "TERBÓCS, István", top: "15%", left: "74%" },
      { name: "SZABAD, Kevin", top: "61%", left: "88%" },
      { name: "TERBÓCS, István", top: "31%", left: "71%" },
      { name: "LANGKOW, Chris", top: "42%", left: "82%" },
      { name: "LANGKOW, Chris", top: "62%", left: "90%" },
      { name: "SZIGETI, Ákos", top: "34%", left: "76%" },
      { name: "BROWN, Jared", top: "47%", left: "19%" },
      { name: "ORBAN, Brance", top: "65%", left: "87%" },
      { name: "TERBÓCS, István", top: "25%", left: "14%" },
      { name: "TERBÓCS, István", top: "23%", left: "14%" }
    ]
  },
  {
    opponent: "HKM Zvolen",
    date: "Nedeľa 09.12.2018, 17:00",
    shots: [
      { name: "BODÓ, Chris", top: "58%", left: "82%" },
      { name: "KLEMPA, Tomáš", top: "42%", left: "83%" },
      { name: "DUDÁS, Jesse Ray", top: "63%", left: "82%" },
      { name: "DANSEREAU, Keegan", top: "61%", left: "87%" },
      { name: "NAGY, Krisztián", top: "57%", left: "81%" },
      { name: "ODNOGA, Mátyás", top: "57%", left: "80%" },
      { name: "DUDÁS, Jesse Ray", top: "63%", left: "81%" },
      { name: "BODÓ, Chris", top: "49%", left: "85%" },
      { name: "DUDÁS, Jesse Ray", top: "47%", left: "88%" },
      { name: "NEGRIN, John", top: "69%", left: "68%" },
      { name: "DUDÁS, Jesse Ray", top: "65%", left: "82%" },
      { name: "DUDÁS, Jesse Ray", top: "64%", left: "87%" },
      { name: "BODÓ, Chris", top: "63%", left: "85%" },
      { name: "KLEMPA, Tomáš", top: "62%", left: "80%" },
      { name: "DUDÁS, Jesse Ray", top: "55%", left: "82%" },
      { name: "DUDÁS, Jesse Ray", top: "60%", left: "85%" },
      { name: "BODÓ, Chris", top: "67%", left: "81%" },
      { name: "POZSGAI, Tamás", top: "60%", left: "81%" },
      { name: "BROWN, Jared", top: "67%", left: "90%" },
      { name: "KLEMPA, Tomáš", top: "53%", left: "84%" },
      { name: "DUDÁS, Jesse Ray", top: "59%", left: "85%" },
      { name: "NEGRIN, John", top: "61%", left: "85%" },
      { name: "BURT, Cameron", top: "62%", left: "81%" },
      { name: "MACAULAY, Scott", top: "53%", left: "86%" },
      { name: "BROWN, Jared", top: "62%", left: "86%" },
      { name: "DUDÁS, Jesse Ray", top: "61%", left: "86%" },
      { name: "BROWN, Jared", top: "61%", left: "83%" },
      { name: "BODÓ, Chris", top: "64%", left: "88%" }
    ]
  },
  {
    opponent: "HC 07 Detva",
    date: "Streda 14.11.2018, 18:00",
    shots: [
      { name: "BROWN, Jared", top: "39%", left: "77%" },
      { name: "KREISZ, Brúnó", top: "71%", left: "79%" },
      { name: "KREISZ, Brúnó", top: "25%", left: "66%" },
      { name: "TERBÓCS, István", top: "47%", left: "75%" },
      { name: "BROWN, Jared", top: "38%", left: "64%" },
      { name: "LANGKOW, Chris", top: "66%", left: "85%" },
      { name: "LANGKOW, Chris", top: "45%", left: "82%" },
      { name: "LANGKOW, Chris", top: "71%", left: "84%" },
      { name: "SZABAD, Kevin", top: "39%", left: "65%" },
      { name: "ORBAN, Brance", top: "44%", left: "73%" },
      { name: "BROWN, Jared", top: "46%", left: "72%" },
      { name: "BROWN, Jared", top: "48%", left: "77%" },
      { name: "KLEMPA, Tomáš", top: "73%", left: "81%" },
      { name: "LANGKOW, Chris", top: "60%", left: "78%" },
      { name: "ORBAN, Brance", top: "35%", left: "73%" },
      { name: "BUGÁR, Gábor", top: "18%", left: "53%" },
      { name: "FEJES, Nándor", top: "40%", left: "35%" },
      { name: "LANGKOW, Chris", top: "52%", left: "22%" },
      { name: "NAGY, Krisztián", top: "43%", left: "25%" },
      { name: "LANGKOW, Chris", top: "53%", left: "22%" },
      { name: "BURT, Cameron", top: "74%", left: "26%" },
      { name: "DUDÁS, Jesse Ray", top: "85%", left: "39%" },
      { name: "DANSEREAU, Keegan", top: "65%", left: "23%" },
      { name: "BROWN, Jared", top: "26%", left: "41%" },
      { name: "BODÓ, Chris", top: "58%", left: "21%" },
      { name: "TERBÓCS, István", top: "69%", left: "21%" },
      { name: "DUDÁS, Jesse Ray", top: "30%", left: "27%" },
      { name: "KLEMPA, Tomáš", top: "77%", left: "30%" },
      { name: "DUDÁS, Jesse Ray", top: "84%", left: "42%" },
      { name: "BUGÁR, Gábor", top: "72%", left: "23%" },
      { name: "POZSGAI, Tamás", top: "83%", left: "75%" },
      { name: "DANSEREAU, Keegan", top: "75%", left: "70%" },
      { name: "DUDÁS, Jesse Ray", top: "40%", left: "73%" },
      { name: "DUDÁS, Jesse Ray", top: "84%", left: "64%" }
    ]
  },
  {
    opponent: "HKM Zvolen",
    date: "Nedeľa 13.01.2019, 17:45",
    shots: [
      { name: "BROWN, Jared", top: "48%", left: "14%" },
      { name: "VOKLA, Roland", top: "85%", left: "34%" },
      { name: "PÁPA, Márton", top: "48%", left: "17%" },
      { name: "BROWN, Jared", top: "86%", left: "76%" },
      { name: "ORBAN, Brance", top: "86%", left: "78%" },
      { name: "SZIGETI, Ákos", top: "55%", left: "79%" },
      { name: "BROWN, Jared", top: "57%", left: "84%" },
      { name: "NAGY, Krisztián", top: "49%", left: "83%" },
      { name: "DANSEREAU, Keegan", top: "54%", left: "80%" },
      { name: "BODÓ, Chris", top: "56%", left: "86%" },
      { name: "BROWN, Jared", top: "31%", left: "83%" },
      { name: "DUDÁS, Jesse Ray", top: "21%", left: "78%" },
      { name: "ORBAN, Brance", top: "48%", left: "73%" },
      { name: "NAGY, Krisztián", top: "79%", left: "22%" },
      { name: "MACAULAY, Scott", top: "27%", left: "13%" },
      { name: "KLEMPA, Tomáš", top: "69%", left: "23%" },
      { name: "BODÓ, Chris", top: "56%", left: "14%" },
      { name: "LANGKOW, Chris", top: "38%", left: "13%" },
      { name: "DUDÁS, Jesse Ray", top: "17%", left: "20%" },
      { name: "NAGY, Krisztián", top: "19%", left: "14%" },
      { name: "LANGKOW, Chris", top: "37%", left: "84%" },
      { name: "BROWN, Jared", top: "54%", left: "21%" }
    ]
  },
  {
    opponent: "MsHK DOXXbet Žilina",
    date: "Nedeľa 02.12.2018, 17:00",
    shots: [
      { name: "SZABAD, Kevin", top: "77%", left: "18%" },
      { name: "KLEMPA, Tomáš", top: "65%", left: "12%" },
      { name: "POZSGAI, Tamás", top: "57%", left: "34%" },
      { name: "POZSGAI, Tamás", top: "50%", left: "35%" },
      { name: "NAGY, Krisztián", top: "80%", left: "19%" },
      { name: "MACAULAY, Scott", top: "26%", left: "32%" },
      { name: "DANSEREAU, Keegan", top: "52%", left: "15%" },
      { name: "POZSGAI, Tamás", top: "75%", left: "16%" },
      { name: "BROWN, Jared", top: "73%", left: "15%" },
      { name: "BROWN, Jared", top: "71%", left: "18%" },
      { name: "NAGY, Krisztián", top: "50%", left: "34%" },
      { name: "POZSGAI, Tamás", top: "52%", left: "33%" },
      { name: "TERBÓCS, István", top: "65%", left: "77%" },
      { name: "BROWN, Jared", top: "38%", left: "77%" },
      { name: "ODNOGA, Mátyás", top: "41%", left: "77%" },
      { name: "MAJOROSS, Barnabás", top: "43%", left: "59%" },
      { name: "NAGY, Krisztián", top: "56%", left: "78%" },
      { name: "BROWN, Jared", top: "78%", left: "75%" },
      { name: "SZABAD, Kevin", top: "41%", left: "79%" },
      { name: "DUDÁS, Jesse Ray", top: "26%", left: "70%" },
      { name: "NAGY, Krisztián", top: "43%", left: "73%" },
      { name: "SZABAD, Kevin", top: "40%", left: "80%" },
      { name: "DANSEREAU, Keegan", top: "56%", left: "64%" },
      { name: "BODÓ, Chris", top: "64%", left: "87%" },
      { name: "DUDÁS, Jesse Ray", top: "19%", left: "30%" },
      { name: "BODÓ, Chris", top: "68%", left: "9%" },
      { name: "DUDÁS, Jesse Ray", top: "70%", left: "16%" },
      { name: "ODNOGA, Mátyás", top: "52%", left: "33%" },
      { name: "FEJES, Nándor", top: "41%", left: "31%" },
      { name: "DUDÁS, Jesse Ray", top: "38%", left: "21%" },
      { name: "BROWN, Jared", top: "23%", left: "18%" },
      { name: "MACAULAY, Scott", top: "44%", left: "21%" },
      { name: "BROWN, Jared", top: "37%", left: "24%" },
      { name: "DANSEREAU, Keegan", top: "40%", left: "23%" },
      { name: "DUDÁS, Jesse Ray", top: "73%", left: "20%" },
      { name: "BROWN, Jared", top: "68%", left: "19%" },
      { name: "TERBÓCS, István", top: "42%", left: "22%" },
      { name: "DUDÁS, Jesse Ray", top: "18%", left: "35%" },
      { name: "SZABAD, Kevin", top: "74%", left: "24%" },
      { name: "DUDÁS, Jesse Ray", top: "46%", left: "31%" },
      { name: "TERBÓCS, István", top: "39%", left: "22%" }
    ]
  },
  {
    opponent: "MHk 32 Liptovský Mikuláš",
    date: "Utorok 27.11.2018, 19:00",
    shots: [
      { name: "LANGKOW, Chris", top: "27%", left: "18%" },
      { name: "BROWN, Jared", top: "83%", left: "27%" },
      { name: "KLEMPA, Tomáš", top: "48%", left: "16%" },
      { name: "DANSEREAU, Keegan", top: "21%", left: "18%" },
      { name: "DUDÁS, Jesse Ray", top: "78%", left: "26%" },
      { name: "BODÓ, Chris", top: "87%", left: "25%" },
      { name: "ODNOGA, Mátyás", top: "80%", left: "14%" },
      { name: "NEGRIN, John", top: "46%", left: "32%" },
      { name: "DANSEREAU, Keegan", top: "37%", left: "10%" },
      { name: "BROWN, Jared", top: "28%", left: "39%" },
      { name: "BODÓ, Chris", top: "85%", left: "70%" },
      { name: "TERBÓCS, István", top: "39%", left: "86%" },
      { name: "KLEMPA, Tomáš", top: "18%", left: "77%" },
      { name: "KLEMPA, Tomáš", top: "18%", left: "81%" },
      { name: "NAGY, Krisztián", top: "49%", left: "85%" },
      { name: "NAGY, Krisztián", top: "48%", left: "81%" },
      { name: "NAGY, Krisztián", top: "51%", left: "73%" },
      { name: "TERBÓCS, István", top: "56%", left: "82%" },
      { name: "BODÓ, Chris", top: "21%", left: "86%" },
      { name: "DANSEREAU, Keegan", top: "59%", left: "73%" },
      { name: "MACAULAY, Scott", top: "73%", left: "70%" },
      { name: "NAGY, Krisztián", top: "47%", left: "83%" },
      { name: "DANSEREAU, Keegan", top: "63%", left: "81%" },
      { name: "DUDÁS, Jesse Ray", top: "41%", left: "65%" },
      { name: "KLEMPA, Tomáš", top: "57%", left: "89%" },
      { name: "DANSEREAU, Keegan", top: "30%", left: "65%" },
      { name: "LANGKOW, Chris", top: "17%", left: "79%" },
      { name: "BODÓ, Chris", top: "51%", left: "87%" },
      { name: "KREISZ, Brúnó", top: "77%", left: "77%" },
      { name: "BROWN, Jared", top: "63%", left: "14%" },
      { name: "FEJES, Nándor", top: "68%", left: "31%" },
      { name: "KREISZ, Brúnó", top: "32%", left: "14%" },
      { name: "DANSEREAU, Keegan", top: "28%", left: "16%" },
      { name: "LANGKOW, Chris", top: "30%", left: "19%" },
      { name: "DUDÁS, Jesse Ray", top: "47%", left: "34%" },
      { name: "BROWN, Jared", top: "65%", left: "17%" },
      { name: "KLEMPA, Tomáš", top: "52%", left: "13%" },
      { name: "FEJES, Nándor", top: "39%", left: "12%" }
    ]
  },
  {
    opponent: "HC ‘05 iClinic Banská Bystrica",
    date: "Piatok 23.11.2018, 19:00",
    shots: [
      { name: "NEGRIN, John", top: "25%", left: "14%" },
      { name: "KLEMPA, Tomáš", top: "60%", left: "11%" },
      { name: "BODÓ, Chris", top: "64%", left: "13%" },
      { name: "BODÓ, Chris", top: "59%", left: "18%" },
      { name: "DUDÁS, Jesse Ray", top: "4%", left: "34%" },
      { name: "NEGRIN, John", top: "39%", left: "30%" },
      { name: "NAGY, Krisztián", top: "29%", left: "13%" },
      { name: "KLEMPA, Tomáš", top: "31%", left: "81%" },
      { name: "BODÓ, Chris", top: "24%", left: "82%" },
      { name: "SZIGETI, Ákos", top: "69%", left: "74%" },
      { name: "POZSGAI, Tamás", top: "15%", left: "71%" },
      { name: "DANSEREAU, Keegan", top: "92%", left: "53%" },
      { name: "BODÓ, Chris", top: "29%", left: "32%" },
      { name: "MAJOROSS, Barnabás", top: "52%", left: "33%" },
      { name: "POZSGAI, Tamás", top: "49%", left: "41%" },
      { name: "MAJOROSS, Barnabás", top: "46%", left: "33%" },
      { name: "POZSGAI, Tamás", top: "67%", left: "28%" },
      { name: "TERBÓCS, István", top: "23%", left: "13%" },
      { name: "TERBÓCS, István", top: "38%", left: "10%" },
      { name: "NAGY, Krisztián", top: "57%", left: "33%" }
    ]
  },
  {
    opponent: "HK ORANGE 20",
    date: "Utorok 04.12.2018, 17:00",
    shots: [
      { name: "DUDÁS, Jesse Ray", top: "44%", left: "67%" },
      { name: "VOKLA, Roland", top: "1%", left: "78%" },
      { name: "PÁPA, Márton", top: "80%", left: "70%" },
      { name: "BODÓ, Chris", top: "32%", left: "82%" },
      { name: "MACAULAY, Scott", top: "2%", left: "69%" },
      { name: "ODNOGA, Mátyás", top: "86%", left: "68%" },
      { name: "PÁPA, Márton", top: "58%", left: "78%" },
      { name: "MAJOROSS, Barnabás", top: "43%", left: "82%" },
      { name: "DANSEREAU, Keegan", top: "44%", left: "80%" },
      { name: "DANSEREAU, Keegan", top: "36%", left: "77%" },
      { name: "SZABAD, Kevin", top: "12%", left: "78%" },
      { name: "MAJOROSS, Barnabás", top: "43%", left: "69%" },
      { name: "KLEMPA, Tomáš", top: "44%", left: "83%" },
      { name: "KLEMPA, Tomáš", top: "30%", left: "83%" },
      { name: "BODÓ, Chris", top: "34%", left: "87%" },
      { name: "DUDÁS, Jesse Ray", top: "44%", left: "68%" },
      { name: "VOKLA, Roland", top: "80%", left: "15%" },
      { name: "LANGKOW, Chris", top: "56%", left: "29%" },
      { name: "BURT, Cameron", top: "84%", left: "31%" },
      { name: "KEDVES, Richárd", top: "16%", left: "19%" },
      { name: "BODÓ, Chris", top: "50%", left: "27%" },
      { name: "LANGKOW, Chris", top: "30%", left: "11%" },
      { name: "NEGRIN, John", top: "58%", left: "31%" },
      { name: "SZABAD, Kevin", top: "39%", left: "34%" },
      { name: "SZABAD, Kevin", top: "43%", left: "11%" },
      { name: "DUDÁS, Jesse Ray", top: "82%", left: "11%" },
      { name: "BODÓ, Chris", top: "74%", left: "10%" },
      { name: "BODÓ, Chris", top: "18%", left: "86%" },
      { name: "BROWN, Jared", top: "43%", left: "73%" },
      { name: "BODÓ, Chris", top: "15%", left: "78%" },
      { name: "ODNOGA, Mátyás", top: "8%", left: "74%" },
      { name: "KEDVES, Richárd", top: "26%", left: "81%" },
      { name: "KLEMPA, Tomáš", top: "7%", left: "84%" },
      { name: "BROWN, Jared", top: "64%", left: "84%" },
      { name: "LANGKOW, Chris", top: "14%", left: "69%" },
      { name: "NEGRIN, John", top: "50%", left: "64%" },
      { name: "MACAULAY, Scott", top: "68%", left: "74%" }
    ]
  },
  {
    opponent: "HC ‘05 iClinic Banská Bystrica",
    date: "Piatok 28.12.2018, 17:30",
    shots: [
      { name: "DANSEREAU, Keegan", top: "20%", left: "80%" },
      { name: "LANGKOW, Chris", top: "65%", left: "14%" },
      { name: "MACAULAY, Scott", top: "54%", left: "18%" },
      { name: "TERBÓCS, István", top: "50%", left: "17%" },
      { name: "BODÓ, Chris", top: "50%", left: "81%" },
      { name: "LANGKOW, Chris", top: "76%", left: "86%" },
      { name: "LANGKOW, Chris", top: "49%", left: "82%" },
      { name: "NEGRIN, John", top: "28%", left: "68%" },
      { name: "LANGKOW, Chris", top: "59%", left: "83%" },
      { name: "ORBAN, Brance", top: "71%", left: "77%" },
      { name: "PÁPA, Márton", top: "52%", left: "85%" },
      { name: "BODÓ, Chris", top: "44%", left: "84%" }
    ]
  },
  {
    opponent: "HK Nitra",
    date: "Nedeľa 06.01.2019, 16:00",
    shots: [
      { name: "SZABAD, Kevin", top: "69%", left: "18%" },
      { name: "GARÁT, Zsombor", top: "78%", left: "30%" },
      { name: "KREISZ, Brúnó", top: "83%", left: "22%" },
      { name: "DANSEREAU, Keegan", top: "21%", left: "23%" },
      { name: "DANSEREAU, Keegan", top: "40%", left: "16%" },
      { name: "GARÁT, Zsombor", top: "72%", left: "30%" },
      { name: "KLEMPA, Tomáš", top: "81%", left: "16%" },
      { name: "BROWN, Jared", top: "19%", left: "11%" },
      { name: "POZSGAI, Tamás", top: "30%", left: "32%" },
      { name: "SZABAD, Kevin", top: "59%", left: "28%" },
      { name: "ORBAN, Brance", top: "21%", left: "23%" },
      { name: "TERBÓCS, István", top: "21%", left: "22%" },
      { name: "ORBAN, Brance", top: "70%", left: "86%" },
      { name: "ORBAN, Brance", top: "68%", left: "68%" },
      { name: "FEJES, Nándor", top: "48%", left: "40%" },
      { name: "BODÓ, Chris", top: "20%", left: "69%" },
      { name: "MAJOROSS, Barnabás", top: "78%", left: "74%" },
      { name: "GARÁT, Zsombor", top: "21%", left: "17%" },
      { name: "BODÓ, Chris", top: "51%", left: "81%" },
      { name: "BROWN, Jared", top: "31%", left: "80%" },
      { name: "BURT, Cameron", top: "74%", left: "69%" },
      { name: "BROWN, Jared", top: "69%", left: "86%" },
      { name: "BROWN, Jared", top: "33%", left: "89%" },
      { name: "LANGKOW, Chris", top: "36%", left: "13%" },
      { name: "TERBÓCS, István", top: "36%", left: "15%" },
      { name: "BROWN, Jared", top: "19%", left: "2%" },
      { name: "SZIGETI, Ákos", top: "22%", left: "41%" },
      { name: "SZABAD, Kevin", top: "30%", left: "15%" },
      { name: "GARÁT, Zsombor", top: "15%", left: "30%" },
      { name: "PÁPA, Márton", top: "38%", left: "11%" },
      { name: "VOKLA, Roland", top: "76%", left: "18%" },
      { name: "SZIGETI, Ákos", top: "53%", left: "21%" },
      { name: "MAJOROSS, Barnabás", top: "26%", left: "18%" },
      { name: "PÁPA, Márton", top: "77%", left: "27%" },
      { name: "SZIGETI, Ákos", top: "65%", left: "27%" }
    ]
  },
  {
    opponent: "DVTK Jegesmedvék Miskolc",
    date: "Piatok 21.12.2018, 18:00",
    shots: [
      { name: "DANSEREAU, Keegan", top: "71%", left: "22%" },
      { name: "DANSEREAU, Keegan", top: "49%", left: "15%" },
      { name: "KLEMPA, Tomáš", top: "41%", left: "31%" },
      { name: "LANGKOW, Chris", top: "30%", left: "23%" },
      { name: "BURT, Cameron", top: "60%", left: "16%" },
      { name: "MACAULAY, Scott", top: "69%", left: "24%" },
      { name: "KLEMPA, Tomáš", top: "27%", left: "14%" },
      { name: "DUDÁS, Jesse Ray", top: "60%", left: "28%" },
      { name: "POZSGAI, Tamás", top: "49%", left: "27%" },
      { name: "KLEMPA, Tomáš", top: "43%", left: "28%" },
      { name: "VOKLA, Roland", top: "76%", left: "27%" },
      { name: "BODÓ, Chris", top: "29%", left: "25%" },
      { name: "DUDÁS, Jesse Ray", top: "23%", left: "30%" },
      { name: "PÁPA, Márton", top: "71%", left: "13%" },
      { name: "MACAULAY, Scott", top: "29%", left: "30%" },
      { name: "BODÓ, Chris", top: "38%", left: "85%" },
      { name: "LANGKOW, Chris", top: "63%", left: "85%" },
      { name: "DANSEREAU, Keegan", top: "57%", left: "72%" },
      { name: "MACAULAY, Scott", top: "51%", left: "71%" },
      { name: "NAGY, Krisztián", top: "61%", left: "77%" },
      { name: "TERBÓCS, István", top: "25%", left: "81%" },
      { name: "BODÓ, Chris", top: "66%", left: "85%" },
      { name: "MACAULAY, Scott", top: "28%", left: "43%" },
      { name: "TERBÓCS, István", top: "67%", left: "21%" },
      { name: "VOKLA, Roland", top: "71%", left: "19%" },
      { name: "DUDÁS, Jesse Ray", top: "27%", left: "21%" },
      { name: "DANSEREAU, Keegan", top: "27%", left: "40%" },
      { name: "LANGKOW, Chris", top: "34%", left: "24%" },
      { name: "NEGRIN, John", top: "62%", left: "47%" },
      { name: "TERBÓCS, István", top: "29%", left: "20%" },
      { name: "MACAULAY, Scott", top: "28%", left: "27%" },
      { name: "BODÓ, Chris", top: "47%", left: "12%" },
      { name: "NEGRIN, John", top: "72%", left: "32%" },
      { name: "DANSEREAU, Keegan", top: "19%", left: "25%" }
    ]
  },
  {
    opponent: "HC Košice",
    date: "Piatok 07.12.2018, 18:00",
    shots: [
      { name: "LANGKOW, Chris", top: "54%", left: "14%" },
      { name: "BODÓ, Chris", top: "91%", left: "17%" },
      { name: "TERBÓCS, István", top: "38%", left: "10%" },
      { name: "PÁPA, Márton", top: "54%", left: "13%" },
      { name: "SZIGETI, Ákos", top: "26%", left: "45%" },
      { name: "POZSGAI, Tamás", top: "16%", left: "66%" },
      { name: "PÁPA, Márton", top: "42%", left: "83%" },
      { name: "KLEMPA, Tomáš", top: "48%", left: "76%" },
      { name: "MACAULAY, Scott", top: "81%", left: "76%" },
      { name: "DUDÁS, Jesse Ray", top: "80%", left: "70%" },
      { name: "KLEMPA, Tomáš", top: "47%", left: "69%" },
      { name: "NAGY, Krisztián", top: "33%", left: "84%" },
      { name: "NAGY, Krisztián", top: "29%", left: "20%" },
      { name: "MACAULAY, Scott", top: "64%", left: "31%" },
      { name: "LANGKOW, Chris", top: "26%", left: "17%" },
      { name: "BODÓ, Chris", top: "22%", left: "14%" },
      { name: "DUDÁS, Jesse Ray", top: "15%", left: "52%" },
      { name: "MACAULAY, Scott", top: "75%", left: "29%" },
      { name: "PÁPA, Márton", top: "53%", left: "32%" },
      { name: "DUDÁS, Jesse Ray", top: "80%", left: "33%" },
      { name: "DUDÁS, Jesse Ray", top: "86%", left: "26%" },
      { name: "BODÓ, Chris", top: "27%", left: "23%" },
      { name: "BROWN, Jared", top: "61%", left: "41%" },
      { name: "BODÓ, Chris", top: "24%", left: "23%" },
      { name: "DUDÁS, Jesse Ray", top: "60%", left: "17%" }
    ]
  },
  {
    opponent: "HC 07 Detva",
    date: "Streda 19.12.2018, 19:00",
    shots: [
      { name: "SZABAD, Kevin", top: "77%", left: "23%" },
      { name: "TERBÓCS, István", top: "59%", left: "13%" },
      { name: "BURT, Cameron", top: "56%", left: "14%" },
      { name: "NAGY, Krisztián", top: "67%", left: "24%" },
      { name: "BODÓ, Chris", top: "76%", left: "27%" },
      { name: "KLEMPA, Tomáš", top: "74%", left: "26%" },
      { name: "TERBÓCS, István", top: "59%", left: "78%" },
      { name: "KLEMPA, Tomáš", top: "51%", left: "78%" },
      { name: "NEGRIN, John", top: "16%", left: "87%" },
      { name: "BODÓ, Chris", top: "29%", left: "75%" },
      { name: "KLEMPA, Tomáš", top: "51%", left: "72%" },
      { name: "NEGRIN, John", top: "51%", left: "73%" },
      { name: "ODNOGA, Mátyás", top: "47%", left: "69%" },
      { name: "POZSGAI, Tamás", top: "30%", left: "68%" },
      { name: "DANSEREAU, Keegan", top: "54%", left: "70%" },
      { name: "NEGRIN, John", top: "47%", left: "81%" },
      { name: "NAGY, Krisztián", top: "68%", left: "76%" },
      { name: "NAGY, Krisztián", top: "79%", left: "77%" },
      { name: "MACAULAY, Scott", top: "41%", left: "15%" },
      { name: "DUDÁS, Jesse Ray", top: "24%", left: "37%" },
      { name: "DUDÁS, Jesse Ray", top: "63%", left: "22%" },
      { name: "KLEMPA, Tomáš", top: "49%", left: "17%" },
      { name: "DANSEREAU, Keegan", top: "70%", left: "24%" },
      { name: "TERBÓCS, István", top: "38%", left: "12%" },
      { name: "BROWN, Jared", top: "33%", left: "3%" },
      { name: "BODÓ, Chris", top: "27%", left: "16%" },
      { name: "PÁPA, Márton", top: "43%", left: "23%" },
      { name: "DANSEREAU, Keegan", top: "47%", left: "82%" },
      { name: "NEGRIN, John", top: "47%", left: "82%" },
      { name: "BODÓ, Chris", top: "21%", left: "17%" },
      { name: "BURT, Cameron", top: "40%", left: "23%" },
      { name: "KLEMPA, Tomáš", top: "47%", left: "20%" },
      { name: "DUDÁS, Jesse Ray", top: "38%", left: "24%" },
      { name: "DUDÁS, Jesse Ray", top: "46%", left: "34%" },
      { name: "DANSEREAU, Keegan", top: "37%", left: "14%" },
      { name: "BROWN, Jared", top: "48%", left: "14%" }
    ]
  },
  {
    opponent: "MsHK DOXXbet Žilina",
    date: "Streda 31.10.2018, 19:00",
    shots: [
      { name: "LANGKOW, Chris", top: "86%", left: "33%" },
      { name: "MAJOROSS, Barnabás", top: "40%", left: "9%" },
      { name: "LANGKOW, Chris", top: "63%", left: "11%" },
      { name: "TERBÓCS, István", top: "22%", left: "24%" },
      { name: "KLEMPA, Tomáš", top: "61%", left: "14%" },
      { name: "KLEMPA, Tomáš", top: "50%", left: "14%" },
      { name: "BUKOR, Raymond", top: "85%", left: "68%" },
      { name: "ORBAN, Brance", top: "64%", left: "77%" },
      { name: "TERBÓCS, István", top: "55%", left: "84%" },
      { name: "BUKOR, Raymond", top: "41%", left: "85%" },
      { name: "BUKOR, Raymond", top: "60%", left: "85%" },
      { name: "POZSGAI, Tamás", top: "43%", left: "67%" },
      { name: "SZIGETI, Ákos", top: "58%", left: "67%" },
      { name: "KLEMPA, Tomáš", top: "52%", left: "83%" },
      { name: "KREISZ, Brúnó", top: "45%", left: "81%" },
      { name: "BUGÁR, Gábor", top: "84%", left: "67%" },
      { name: "DUDÁS, Jesse Ray", top: "29%", left: "83%" },
      { name: "ODNOGA, Mátyás", top: "32%", left: "44%" },
      { name: "LANGKOW, Chris", top: "51%", left: "17%" },
      { name: "BODÓ, Chris", top: "21%", left: "15%" },
      { name: "KLEMPA, Tomáš", top: "76%", left: "24%" },
      { name: "DANSEREAU, Keegan", top: "59%", left: "8%" },
      { name: "DANSEREAU, Keegan", top: "39%", left: "8%" },
      { name: "ORBAN, Brance", top: "52%", left: "14%" },
      { name: "BODÓ, Chris", top: "25%", left: "12%" },
      { name: "LANGKOW, Chris", top: "42%", left: "23%" }
    ]
  },
  {
    opponent: "HKM Zvolen",
    date: "Nedeľa 04.11.2018, 18:00",
    shots: [
      { name: "TERBÓCS, István", top: "33%", left: "12%" },
      { name: "NAGY, Krisztián", top: "11%", left: "31%" },
      { name: "SZIGETI, Ákos", top: "62%", left: "24%" },
      { name: "LANGKOW, Chris", top: "7%", left: "32%" },
      { name: "DANSEREAU, Keegan", top: "41%", left: "11%" },
      { name: "ORBAN, Brance", top: "72%", left: "78%" },
      { name: "NAGY, Krisztián", top: "63%", left: "90%" },
      { name: "DANSEREAU, Keegan", top: "61%", left: "82%" },
      { name: "TERBÓCS, István", top: "28%", left: "85%" },
      { name: "SZIGETI, Ákos", top: "42%", left: "85%" },
      { name: "DUDÁS, Jesse Ray", top: "33%", left: "82%" },
      { name: "DANSEREAU, Keegan", top: "51%", left: "26%" },
      { name: "KLEMPA, Tomáš", top: "80%", left: "33%" },
      { name: "BODÓ, Chris", top: "7%", left: "11%" },
      { name: "BROWN, Jared", top: "52%", left: "14%" },
      { name: "DANSEREAU, Keegan", top: "28%", left: "18%" },
      { name: "POZSGAI, Tamás", top: "93%", left: "33%" },
      { name: "BODÓ, Chris", top: "48%", left: "20%" },
      { name: "BROWN, Jared", top: "48%", left: "21%" },
      { name: "LANGKOW, Chris", top: "25%", left: "21%" },
      { name: "DUDÁS, Jesse Ray", top: "66%", left: "25%" }
    ]
  }
]
export default data
